jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Pull & rebase prima delle modifiche
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git pull --rebase

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installa dipendenze
        run: pip install requests

      - name: Esegui script m3u
        run: python script_m3u.py

      - name: Commit & push se serve
        run: |
          if git diff --quiet; then
            echo "Nessuna modifica da pushare."
          else
            git add iptvitaplus.m3u
            git commit -m "Aggiornamento automatico della lista m3u"
            git push
          fi
